### ISSUE TITLE
Patching dependencies in Fedora

### ISSUE THREAD

**Issue by LorbusChris** [LorbusChris/nextcloud-rpm#1]
Some dependencies require to be patched.

See https://bugzilla.redhat.com/show_bug.cgi?id=1433919#c28

**Comment by MagnumGR** [comment]
As you can see in https://bugzilla.redhat.com/show_bug.cgi?id=1433919, all the missing deps has been prepared .

**Comment by LorbusChris** [comment]
I updated the title and description to reflect the current state.

There is also more work required in the spec. Will resume once I find some time. Until that, WIP.

**Comment by MagnumGR** [comment]
Nextcloud 13 just released: https://nextcloud.com/blog/nextcloud-13-brings-secure-file-sync-and-collaboration-to-the-next-level/
